theme: jekyll-theme-minimal
markdown: kramdown

title: Global Biodiversity Decline & Individual Action
description: Final project website for Foundational Biology at Olin College, Fall 2020

logo: "logo.JPG"
show_downloads: "false"

